name: Develop CI

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - ".github/workflows/*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.DEADV_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          forceOrphan: true
  sync:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.IVEIW_DEPLOY_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Aaron52077/vue-iview-admin.git"
          destination-repo: "git@gitee.com:wuli-admin/vue-iview-admin.git"

  reload-pages:
    needs: sync
    runs-on: ubuntu-latest

    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: Aaron52077
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: wuli-admin/vue-iview-admin
          branch: gh-pages,
          https: true
